### PR TITLE
Add cx_oracle

### PR DESCRIPTION
**Pull request by mciupak**
Following home-assistant/core#50090 and [pvizeli's comment](https://github.com/home-assistant/docker/pull/191#issuecomment-862442689) could you please add python package cx_oracle to the image?

### CODE REVIEW

**Comment by pvizeli** [comment]
Please remove the submodule

**Comment by mciupak** [comment]
> Please remove the submodule

Removed.

**Comment by pvizeli** [comment]
You need to rebase the PR on top of this repo

**Comment by mciupak** [comment]
> You need to rebase the PR on top of this repo

Done.

**Review by pvizeli — APPROVED** [review]

**Pull request merged**
