### PR TITLE
Add mariadb-connector-c to Dockerfile

### PR DESCRIPTION
**Pull request by bdraco**
fixes https://github.com/home-assistant/core/issues/74539

### CODE REVIEW

**Comment by bdraco** [comment]
This was removed in #236 but apparently still needed

**Comment by pvizeli** [comment]
https://pkgs.alpinelinux.org/contents?file=caching_sha2_password.so&path=&name=&branch=v3.16

**Review by pvizeli — APPROVED** [review]

**Comment by christianreiss** [comment]
> apparently still needed

_Apparently?_ It is the _recommended way_ of doing authentication. The old native Password should not be used anymore.

```
Important
In MySQL 8.0, caching_sha2_password is the default authentication plugin rather than mysql_native_password. 
```
https://dev.mysql.com/doc/refman/8.0/en/caching-sha2-pluggable-authentication.html

The old password method should be removed; if at all.

**Comment by frenck** [comment]
> Apparently? It is the recommended way of doing authentication. The old native Password should not be used anymore.
Its already merged...

**Comment by Brunty** [comment]
Any word on when this might get released?

**Pull request merged**
