### PR TITLE
add gammu

### PR DESCRIPTION
**Pull request by Gloird**
Added gammu to make SMS integration work again

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @Gloird, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;docker#249).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by pvizeli** [comment]
Can you refence to an issue? We use musllinux wheels, so if the python library don't load it on runtime, it's not needed

**Comment by frenck** [comment]
It uses the gammu binary directly from the library.

**Comment by pvizeli** [comment]
I did look into the library and they get compiled, so the auditwheel fix the linking and package the libs into the python package

**Comment by ocalvo** [comment]
Keep alive

**Comment by pvizeli** [comment]
Again, there is no link error show. Our wheels include all binaries.

**Comment by Gloird** [comment]
How can we move forward on this problem please?

**Comment by Gloird** [comment]
The problem : 

image

image

**Comment by frenck** [comment]
Closing this PR. At this point, I don't think this is the right path, and the problem pointed out above makes it impossible to action this PR.

../Frenck

**Pull request closed without merging**
