### PR TITLE
Add mailcap to provide /etc/mime.types

### LINKED ISSUE #134: mime.types files missing on container
Using supervised install on homeassistant
tried to use media_source and found out that my ogg files was not correctly detected as mimetype 'audio'

behavior:
`mimetypes.guess_type('1.ogg')
(None, None)`

expected behavior:
`mimetypes.guess_type('1.ogg')
('audio/ogg', None)`
 
seems that homeassistant is missing mimetype spec files:

`import mimetypes
mimetypes.knownfiles 
['/etc/mime.types', '/etc/httpd/mime.types', '/etc/httpd/conf/mime.types', '/etc/apache/mime.types', '/etc/apache2/mime.types', '/usr/local/etc/httpd/conf/mime.types', '/usr/local/lib/netscape/mime.types', '/usr/local/etc/httpd/conf/mime.types', '/usr/local/etc/mime.types']`

i installed mailcap https://pkgs.alpinelinux.org/package/edge/main/x86_64/mailcap to provide /etc/mime.types file

`docker exec -it homeassistant bash
 apk add mailcap`

and after that mimetypes for ogg files were correctly shown

### PR DESCRIPTION
**Pull request by rigrig**
Fixes #134 
I'm not entirely sure if this is the right place for this, maybe it should go into https://github.com/home-assistant/docker-base instead?

### CODE REVIEW

**Comment by pvizeli** [comment]
We do not install somethings because they include a file which we want. In that case we can just provide our own file

**Comment by rigrig** [comment]
Fair enough, I figured the mailcap package only contains `/etc/mailcap` and `/etc/mime.types` so that would be easier than keeping `/etc/mime.types` up to date here.   
Would adding the file like this be ok? If so I'll see about adding some comments about where it came from.

**Comment by pvizeli** [comment]
Let's use that one: https://github.com/apache/httpd/blob/trunk/docs/conf/mime.types and add this link also into the comment

**Comment by rigrig** [comment]
Ok, copied.

And... just noticed that it won't solve my particular case of `.opus` files :-(  Guess I've got another repo to fork.

**Review by pvizeli — APPROVED** [review]

**Comment by pvizeli** [comment]
We can maintain our own mime.types

Just copy https://github.com/nginx/nginx/blob/master/conf/mime.types - change the style and we maintain itself. I don't think there are a lot of changes. That one from alpine was over 5 years old.

**Pull request merged**
