### PR TITLE
Add Oracle DB libraries

### PR DESCRIPTION
**Pull request by mciupak**
Following home-assistant/core#50090 I would like to add cx_oracle and Oracle Instant Client libraries to docker image to be able to use recorder with Oracle DB out of the box.

### CODE REVIEW

**Review by pvizeli — COMMENTED** [review]
I vote against this contribution:
- Licence issue
- Binary blobs

If Oracle does his stuff opensource and releases an official alpine package, we can speak about it.

**Comment by frenck** [comment]
I agree, I was looking at the same.

It will also add 30+ megabytes to every image we ship, while the effective use might be considered fairly minimal.

**Comment by mciupak** [comment]
Understood, fair enough, then I got two ideas/questions:
1) Can we add cx_oracle at least? Instant Client libraries are needed to access cloud based DB instances, but local instances does not require it and can be handled by sqlalchemy with cx_oracle only.
2) Can we think about kind of additional secondary set of base image with Oracle binaries included anyhow?

**Comment by balloob** [comment]
I also agree on not adding it. 

Local Oracle databases… if people pay for a DB like that, they can maintain their own images. Not something we want to maintain.

**Comment by pvizeli** [comment]
Using the python package is fine for me

**Comment by ryansun96** [comment]
> 
> 
> I also agree on not adding it.
> 
> Local Oracle databases… if people pay for a DB like that, they can maintain their own images. Not something we want to maintain.

@balloob Actually Oracle now offers (always) free database instances in their oracle cloud free tier with a 20GB storage quota. So folks (including me) who want to use Oracle with their HA might not necessarily be big corporations...

**Comment by balloob** [comment]
See the activity entry right above your comment. It's been added.

**Comment by ryansun96** [comment]
I'm talking about client libraries.

**Comment by pvizeli** [comment]
We only allow install open-source packages. No way to add this client and no plan to make different images

**Pull request closed without merging**
